#!/bin/bash

set -ex

max_jobs=1

while getopts ":f:r:c:m:" opt; do
  case ${opt} in
    f )
      csv_file=$OPTARG
      ;;
    r )
      script_repo=$OPTARG
      ;;
    c )
      conda=$OPTARG
      ;;
    m )
      max_jobs=$OPTARG
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      ;;
    : )
      echo "Invalid option: $OPTARG requires atleast 3 arguments" 1>&2
      ;;
  esac
done
shift $((OPTIND -1))


index=0
pids=""

{
    read  # Extra read to ignore header
    while IFS=, read -r cell_id
    do
        echo "Launching optimization for $cell_id"
        nohup launch_optimjob --cell_id $cell_id --ext_scripts $script_repo --conda_env $conda > out$index.log 2> err$index.log &
        pids+="$! "
        index=$(($index+1))
        if [[ $index = $max_jobs ]]; then
            break
        fi
    done
}< $csv_file

wait $pids

rm -rf err*.log out*.log
echo "# of jobs submitted = $index"

